name: Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build tests
        run: ./build-tests.sh
      - name: Run tests
        run: ./run-tests.sh